export const NavigationString = {
  Splash: 'Splash',
  OnBoarding: 'OnBoarding',
  Welcome: 'Welcome',
  SignUp: 'SignUp',
  SignIn: 'SignIn',
  Login: 'Login',
  OtpVerify: 'OtpVerify',
  SetPassword: 'SetPassword',
  CompleteProfile: 'CompleteProfile',
  Home: 'Home',
  Profile: 'Profile',
  BottomTabStacks: 'BottomTabStacks',
  DrawerStacks: 'DrawerStacks',
  Favourite: 'Favourite',
  Offers: 'Offers',
  Wallet: 'Wallet',
  SelectPath: 'SelectPath',
  SelectTransport: 'SelectTransport',
  AvailableTransport: 'AvailableTransport',
  VehicleDetail: 'VehicleDetail',
  ConfirmBooking: 'ConfirmBooking',
  BookingThanks: 'BookingThanks',
  Notifications: 'Notifications',
  ViewAllTransections: 'ViewAllTransections',
  AddMoney: 'AddMoney',
  History: 'History',
  Complain: 'Complain',
  Referral: 'Referral',
  AboutUs: 'AboutUs',
  HelpSupport: 'HelpSupport',
  Settings : 'Settings',
  PrivacyPolicy : 'PrivacyPolicy',
  ChangePassword : 'ChangePassword',
  ContactUs : 'ContactUs',
  DeleteAccount : 'DeleteAccount',
  BikeCard:'BikeCard',
  CarCard:'CarCard',
  ForgotPassword:'ForgetPassword',
 ConfrimRide:'ConfrimRide',
 ChatScreen:'ChatScreen',
 CallScreen:'CallScreen',
 TermsAndCondition:'TermsAndCondition',
 RideWaiting: 'RideWaiting',
};
